### ISSUE TITLE
Use plain english text

### ISSUE THREAD

**Issue by dkern** [kayo5994/gulp-file-sync#3]
You should use english text an messages to support a wider range of users. I'm unable to understand what the script wants to tell me too ...

Reson for me to don't use it, even when it's a great plugin!

**Comment by dkern** [comment]
In generel I just mean these console outputs:
https://github.com/kayo5994/gulp-file-sync/blob/master/index.js#L155-L167

**Comment by kayo5994** [comment]
I have changed the language of console output into English, please update to version 1.0.7.
Thanks for your suggestion!
