### ISSUE TITLE
Recursive flag not working as desired.

### ISSUE THREAD

**Issue by pitAlex** [kayo5994/gulp-file-sync#4]
Hello,

I've noticed the recursive flag is not working as expected when it comes to having the ignore option as a function. What I expected is that the function is executed inside the sub folder of the source directory as well. But instead for the "file" parameter it will just give the dir name and thus I cannot perform some file exclusion in that sub folder.

Update:
My bad, it seems I was doing something wrong and got to the bottom of it.

**Comment by kayo5994** [comment]
Hello,

Glad you were able to solve this issue. To your original question-- though the `file` parameter works as intended, the `dir` parameter is indeed redundent and doesn't add any value to that function. Thanks for pointing out that.

In that regard, I've removed the `dir` parameter and instead passing `stats` in the referenced commits.

Cheers.

**Comment by kayo5994** [comment]
@pitAlex Welcome to version [2.0.0](https://github.com/kayo5994/gulp-file-sync/releases/tag/2.0.0), which already includes a fix for this issue.

**Comment by pitAlex** [comment]
Cool
